### ISSUE TITLE
support sha512_256?

### ISSUE THREAD

**Issue by aulneau** [paulmillr/noble-hashes#1]
This is great! Love your work @paulmillr!

I maintain the [stacks](https://stacks.co) library [micro-stacks](https://github.com/fungible-systems/micro-stacks), and will likely use noble-hashes for all the hashing needs. We use [`sha512_256`](https://github.com/fungible-systems/micro-stacks/blob/main/src/crypto-extras/crypto-sha/sha512_256.ts) for a few things, would it be possible for you to add this variant to noble-hashes?

🙏

**Comment by paulmillr** [comment]
Hey. Is it the same as sha512().slice(0, 256)?

**Comment by paulmillr** [comment]
I knew about this method for a while; but never really saw a usage. Do you have some specific use case?

**Comment by aulneau** [comment]
> Hey. Is it the same as sha512().slice(0, 256)?

It is not, there are some bytes that change depending on if it's 512/224 or 512/256, here is another implementation: https://github.com/emn178/js-sha512/blob/master/src/sha512.js#L166-L182

> I knew about this method for a while; but never really saw a usage. Do you have some specific use case?

Yeah, [txIds, among other identifiers](https://github.com/fungible-systems/micro-stacks/blob/main/src/transactions/common/utils.ts#L15) in Stacks are sha512/256. I was not present when this choice was made, but in asking someone who was:

> sha512 truncated to 256 bits is just as secure (or more) as the "double sha256" used by bitcoin
> (it's why it's a standard hash function)
> but it's also much faster to compute on most computers
