### ISSUE TITLE
Request for twox/xxhash

### ISSUE THREAD

**Issue by jacogr** [paulmillr/noble-hashes#10]
First off, this is impressive - I have early branches switching to this https://github.com/polkadot-js/common/pull/1188 (also planning on doing secp256k1 & ed25519 - the first also has a PR, the second haven't gotten around to). Anyway, in that bracnch a couple of operations actually beat out Rust WASM. So certainly impressive.

One of the reasons for switching to the `@noble` family (provided I can get the BigInt story right, have a number of React Native users) is the drops in dependencies, size and speed. Finally a library that follows recent ES standards without resorting to Buffer everywhere.

One of my hashing requests would be for xxhash, I'm currently using https://www.npmjs.com/package/xxhashjs and overall quite happy, but once again pulls in yet-another-big-numbers library. I'm guessing this is quite niche for the target audience, however xxhash is used extensively in the Polkadot/Substrate ecosystem in the runtime, so it would certainly be a welcome addition from this side of the fence.

**Comment by paulmillr** [comment]
Thanks for the suggestion. Maybe someone will find it useful and implement it.

**Comment by tjjfvi** [comment]
I just [adapted](
https://github.com/paritytech/capi/blob/f736128478e65dc7ab39f8aa118237e93164410d/hashers/xxhash.ts) @jacogr's [adaptation](https://github.com/polkadot-js/common/blob/40d6a388/packages/util-crypto/src/xxhash/xxhash64.ts
) of [`xxhashjs`](https://github.com/pierrec/js-xxhash/blob/0504e76f3d31a21ae8528a7f590c7289c9e431d2/lib/xxhash64.js) for use in [capi](https://github.com/paritytech/capi). I think this version could be adapted to work in this library quite easily – @paulmillr would you be open to such a contribution?

**Comment by paulmillr** [comment]
I have decided to keep hashes small for now. Don't want to include xxhash. May reconsider this in the future.

Meanwhile, please use @tjjfvi stuff.

**Comment by tjjfvi** [comment]
In that case, if anyone is looking for an xxhash implementation, there's [a TS implementation](https://github.com/paritytech/capi/blob/f736128478e65dc7ab39f8aa118237e93164410d/hashers/xxhash.ts) linked above as well as [a tiny, 100x-faster WASM implementation](https://github.com/paritytech/wat-the-crypto) that I wrote more recently.
