### ISSUE TITLE
tests failed with noble hashes 1.1.1

### ISSUE THREAD

**Issue by pepihasenfuss** [paulmillr/noble-hashes#33]
running the tests failed
this is my output of the tests on a Mac MacOSs 10.15.7

..............
☆ should Scrypt types:
✓ should Scrypt types

☆ should HKDF types:
✓ should HKDF types

☆ should hkdf(sha256) generator:
☓ should hkdf(sha256) generator
(node:19204) UnhandledPromiseRejectionWarning: TypeError: crypto.hkdfSync is not a function
    at /Users/pepsi/Downloads/noble-hashes-1.1.1/test/generator.js:73:16
    at run (/Users/pepsi/Downloads/noble-hashes-1.1.1/node_modules/micro-should/index.js:14:24)
    at /Users/pepsi/Downloads/noble-hashes-1.1.1/node_modules/micro-should/index.js:81:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 542)
(node:19204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
pepsis-iMac:noble-hashes-1.1.1 pepsi$

**Comment by paulmillr** [comment]
Nodejs version? Npm version?

**Comment by pepihasenfuss** [comment]
My fault:

I was using a very old nom version 6.x and an old node version 14.x.x

Updated both and it runs perfectly and the test went through

☆ should rotl big:
✓ should rotl big

☆ should Test generator:
✓ should Test generator
pepsis-iMac:noble-hashes-1.1.1 pepsi$ node --version
v18.3.0
pepsis-iMac:noble-hashes-1.1.1 pepsi$ npm --version
8.12.1
pepsis-iMac:noble-hashes-1.1.1 pepsi$ 

Peter

> Am 13.06.2022 um 12:32 schrieb Paul Miller ***@***.***>:
> 
> Nodejs version? Npm version?
