### ISSUE TITLE
Module not found: Error: Can't resolve './_assert' ... Did you mean '_assert.js'?

### ISSUE THREAD

**Issue by ddresch** [paulmillr/noble-hashes#42]
When using 

```js
import { k12 } from '@noble/hashes/sha3-addons'
```

I ended up with the `Module not found` error. As a quick fix, I needed to change the file `sha3-addons.js` and add the `.js` file extension to the require statement. I'm writing this issue because I'm uncertain if this type of require without the extension is intentional or not.

**Comment by paulmillr** [comment]
That has been fixed in v1.1.1

**Comment by ddresch** [comment]
I'm using version 1.1.5, and it is importing _assert without .js extension.

**Comment by paulmillr** [comment]
published 1.2.0
