### ISSUE TITLE
README claims support for all stable nodejs versions, but crypto.randomValues isn't available in node14

### ISSUE THREAD

**Issue by brandonblack** [paulmillr/noble-hashes#44]
Still has a month or two of support left. Probably not worth fixing :)

**Comment by paulmillr** [comment]
crypto.randomValues is not used in node.js, see import map located in package.json

**Comment by brandonblack** [comment]
https://github.com/paulmillr/noble-hashes/blob/main/src/cryptoNode.ts#L3
https://github.com/paulmillr/noble-hashes/blob/main/src/utils.ts#L200

Sure looks like it uses `webcrypto.randomValues` on nodejs, which doesn't exist in node14.

**Comment by paulmillr** [comment]
hmmmm i've somehow missed this. Wondering whether to release a new version or just wait 2023-04-30 until node 14 is eol.

**Comment by paulmillr** [comment]
ok, whatevs. Will wait until apr 30th. node 14 doesn't matter anymore.
