### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by pkieltyka** [paulmillr/noble-hashes#46]
`import { bytesToHex as toHex, randomBytes } from '@noble/hashes/scrypt';`

should be..

`import { bytesToHex as toHex, randomBytes } from '@noble/hashes/utils';`

**Comment by paulmillr** [comment]
Can you submit a pull request instead of opening an issue?

**Comment by pkieltyka** [comment]
https://github.com/paulmillr/noble-hashes/pull/47
