### ISSUE TITLE
".js" imports are causing issues in Deno

### ISSUE THREAD

**Issue by quentinadam** [paulmillr/noble-hashes#58]
For example, I am trying to use the `blake2b` hash in Deno by importing the following:

```
import { blake2b } from 'https://deno.land/x/hashes@1.3.0/blake2b.ts';
```
But I am getting the following issue:

```
error: Module not found "https://deno.land/x/hashes@1.3.0/_blake2.js".
    at https://deno.land/x/hashes@1.3.0/blake2b.ts:1:42
```

Changing the import statements on the first lines of blake2b.ts to use the ".ts" extension instead of ".js" would solve the issue.

**Comment by paulmillr** [comment]
Changing the import statements to .ts will make the library fail in other environments, which are pure js.

As mentioned in README, for deno, use it with NPM specifier instead: https://github.com/paulmillr/noble-hashes#usage

**Comment by quentinadam** [comment]
Makes sense, thanks for clarifying.
