### ISSUE TITLE
v1.3.0 doesn't build in React Gatsby

### ISSUE THREAD

**Issue by culda** [paulmillr/noble-hashes#60]
**Description**
I have a Gatsby/yarn v3 app and it doesn't build the latest `bip32` and `bip39` libraries. 
The issue is with v1.3.0 of `noble-hashes` that they both depend on, more specifically with the ESM syntax `import * as nc from 'node:crypto'`. 

![image](https://github.com/paulmillr/noble-hashes/assets/48595067/fa64d832-85f4-4b34-bc29-079750acdd71)

**Solution**
The solution for me currently is
```
"resolutions": {
   "@noble/hashes": "1.2.0",
}
```

**Comment by paulmillr** [comment]
There is no issue with noble-crypto. The issue is with your bundler config. Adjust it properly or report to its repo.
