### ISSUE TITLE
Feature request: Add `md5` support

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/noble-hashes#64]
It would be nice to have a modern and dependency-free version of the `md5` hash.

It is still required for non-cryptographic services such as Gravatar.

**Comment by paulmillr** [comment]
I think we can make and host it on gist.github.com, pointing to it in readme, etc, but I don't want to add it to the library, because it's really discouraged, and brings bad vibes.

I've only added sha-1, because ssh/pgp still use it. They don't use md5 though.

**Comment by mahnunchik** [comment]
Yes, `sha-1` and `md5` have bad vibes...

Maybe it may be included in the library as:

```js
import { md5 } from '@noble/hashes/do-not-use-md5';
```

**Comment by mahnunchik** [comment]
For me, yes, for Gravatar.

**Comment by mahnunchik** [comment]
If the library has `md5` it will cover all my hash related stuff for the entire project 😉

**Comment by sublimator** [comment]
> import { md5 } from '@noble/hashes/do-not-use-md5';

haha

**Comment by paulmillr** [comment]
https://gist.github.com/paulmillr/405d7f1efca6e37bee63d6499cd4c8f9 for now

**Comment by larabr** [comment]
> https://gist.github.com/paulmillr/405d7f1efca6e37bee63d6499cd4c8f9 for now

The gist is not accessible anymore, could you share it again? 😁

**Comment by paulmillr** [comment]
@larabr It's in `misc` directory of the repository: https://github.com/paulmillr/noble-hashes/tree/main/test/misc
