### ISSUE TITLE
`isPlainObject` check fails in serverless env

### ISSUE THREAD

**Issue by aulneau** [paulmillr/noble-hashes#70]
When trying to use some of these hashing functions in the context of a serverless environment, such as vercel or cloudfare, this function 

https://github.com/paulmillr/noble-hashes/blob/54c3197fc53bbfa4521b6883eed0e7bd1430beab/src/utils.ts#L163

fails to accept this object `{c:2048,dkLen:64}` as a plain object. 

I have followed it down to this line:

`obj.constructor === Object` never being true. I'd suggest something like this instead:

`obj.constructor.name === 'Object'`

**Comment by aulneau** [comment]
ah, applies to btc-signer, too:

```Wrong object type for transaction options: [object Object]```

**Comment by paulmillr** [comment]
We have other checks, like: `a instanceof Uint8Array`, which, I assume, would also fail in the scenario.

**Comment by aulneau** [comment]
I have tested it: https://github.com/aulneau/noble-edge-bug/blob/main/src/pages/api/index.ts

Here is a reproduction. I'm not familiar with the reliability of constructor.name or not unfortunately.

**Comment by paulmillr** [comment]
I think we can remove `obj.constructor === Object` check. `Object.prototype.toString.call` is already done. That would make it return different result for `({__proto__: []})`, but if tests pass, I think it could work.

The function is used in only a few places.

**Comment by paulmillr** [comment]
@aulneau fixed!
