### ISSUE TITLE
Error publishing on JSR: referenced a JavaScript module without type declarations from a TypeScript module

### ISSUE THREAD

**Issue by alexgleason** [paulmillr/noble-hashes#83]
I am working on getting `nostr-tools` on JSR: https://jsr.io/@nostr/tools

Cross-referencing this: https://github.com/jsr-io/jsr-npm/issues/62

**Comment by paulmillr** [comment]
that doesn’t seem to be our problem.

there is a standalone built file, cjs files, esm files
