### ISSUE TITLE
Usage for storing and comparing passwords

### ISSUE THREAD

**Issue by aurelius-coffee** [paulmillr/noble-hashes#87]
Hi,

I came here following this guide https://lucia-auth.com/tutorials/username-and-password/astro . 

How would one go about using this library for storing and comparing passwords?

Thanks

**Comment by aurelius-coffee** [comment]
and I imagine store the randomly-generated salt alongside the hash in the db and then use it to compare?

**Comment by paulmillr** [comment]
yeah, salt helps
